<?php

namespace App\Tests;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class AdminCategoryControllerTest extends WebTestCase
{
    protected $client;
    protected UrlGeneratorInterface $urlGenerator;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client = static::createClient();
        $userRepository =$this->client->getContainer()->get(UserRepository::class);
        $this->client->loginUser($userRepository->findOneByEmail('bsimonis@example.net'));

        $this->urlGenerator  =  $this->client->getContainer()->get('router');
    }

    public function testGetCorrectSubCategory(): void
    {
        $crawler = $this->client->request('GET', $this->urlGenerator->generate('videos.index', ['name' => 'graphic-card', 'categoryId' => 1]));
        self::assertSame('Nvidia', $crawler->filter('.dropdown-menu li')->text());

        $crawler = $this->client->request('GET', $this->urlGenerator->generate('videos.index', ['name' => 'graphic-card', 'categoryId' => 1]));
        self::assertNotSame('LG', $crawler->filter('.dropdown-menu li')->text());
    }

    public function testGetCorrectNumberOption(): void
    {
        $crawler = $this->client->request('GET', $this->urlGenerator->generate('categories'));
        self::assertCount(15, $crawler->filter('option'));
    }

    public function testCanAccessAdminVideoPage(): void
    {
        $crawler = $this->client->request('GET', $this->urlGenerator->generate('admin.videos.index'));
        $this->assertResponseIsSuccessful();
    }
}
